set timeout 5
lassign $argv program weights_path pos move
spawn $program $weights_path
expect -re "Chess engine by Adam Jedrych .*" {} timeout {exit 1}
send "uci\n"
expect -re "id name \W*" {} timeout {exit 1}
expect -re "id author \W*" {} timeout {exit 1}
expect "" {} timeout {exit 1}
expect "uciok" {} timeout {exit 1}
send "isready\n"
expect "readyok" {} timeout {exit 1}
send "position fen $pos\n"
send "go movetime 4000\n"
expect -re {(info (((depth \d+)|(score ((cp \d+)|(mate -?\d+)))|(nodes \d+)|(nps \d+)|(time \d+)) )* pv \W*\n)*} {} timeout {exit 1}
expect "bestmove $move" {} timeout {exit 1}
send "quit\n"
expect eof
