set timeout 6
lassign $argv program pos move
spawn $program
expect -re "Chess engine by Adam Jedrych .*" {} timeout {exit 1}
send "uci\n"
expect -re "id name \W*" {} timeout {exit 1}
expect -re "id author \W*" {} timeout {exit 1}
expect "" {} timeout {exit 1}
expect "uciok" {} timeout {exit 1}
send "isready\n"
expect "readyok" {} timeout {exit 1}
send "position fen $pos\n"
send "go movetime 5000\n"
expect -re {(info \W*\n)*} {} timeout {exit 1}
expect "bestmove $move" {} timeout {exit 1}
send "quit\n"
expect eof
