set timeout 1
lassign $argv pos
spawn ./build/deepchess
expect -re "Chess engine by Adam Jedrych .*" {} timeout {exit 1}
send "uci\n"
expect -re "id name \W*" {} timeout {exit 1}
expect -re "id author \W*" {} timeout {exit 1}
expect "" {} timeout {exit 1}
expect "uciok" {} timeout {exit 1}
send "isready\n"
expect "readyok" {} timeout {exit 1}
send "position fen $pos\n"
send "go depth 4\n"
expect -re {(info (((depth \d+)|(score ((cp \d+)|(mate -?\d+)))|(nodes \d+)|(nps \d+)|(time \d+)) )* pv \W*\n)*bestmove [a-h][1-8][a-h][1-8][nbrq]?} {} timeout {exit 1}
send "quit\n"
expect eof
